version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - food-delivery-network

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - MONGO_URL=mongodb://mongodb:27017/food-delivery
      - JWT_SECRET=votre_secret_jwt_ici
      - PORT=5000
    depends_on:
      - mongodb
    networks:
      - food-delivery-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - food-delivery-network

volumes:
  mongodb_data:

networks:
  food-delivery-network:
    driver: bridge